# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /cvmfs/sw.hsf.org/spackages6/cmake/3.23.1/x86_64-centos7-gcc11.2.0-opt/l62l5/bin/cmake

# The command to remove a file.
RM = /cvmfs/sw.hsf.org/spackages6/cmake/3.23.1/x86_64-centos7-gcc11.2.0-opt/l62l5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vvicente/ws/CLICPerformance

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vvicente/ws/CLICPerformance/clicConfig

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/cvmfs/sw.hsf.org/spackages6/cmake/3.23.1/x86_64-centos7-gcc11.2.0-opt/l62l5/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/cvmfs/sw.hsf.org/spackages6/cmake/3.23.1/x86_64-centos7-gcc11.2.0-opt/l62l5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/cvmfs/sw.hsf.org/spackages6/cmake/3.23.1/x86_64-centos7-gcc11.2.0-opt/l62l5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/cvmfs/sw.hsf.org/spackages6/cmake/3.23.1/x86_64-centos7-gcc11.2.0-opt/l62l5/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/cvmfs/sw.hsf.org/spackages6/cmake/3.23.1/x86_64-centos7-gcc11.2.0-opt/l62l5/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/cvmfs/sw.hsf.org/spackages6/cmake/3.23.1/x86_64-centos7-gcc11.2.0-opt/l62l5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/cvmfs/sw.hsf.org/spackages6/cmake/3.23.1/x86_64-centos7-gcc11.2.0-opt/l62l5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/cvmfs/sw.hsf.org/spackages6/cmake/3.23.1/x86_64-centos7-gcc11.2.0-opt/l62l5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/cvmfs/sw.hsf.org/spackages6/cmake/3.23.1/x86_64-centos7-gcc11.2.0-opt/l62l5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vvicente/ws/CLICPerformance/clicConfig/CMakeFiles /home/vvicente/ws/CLICPerformance/clicConfig//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vvicente/ws/CLICPerformance/clicConfig/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named ClicPerformance

# Build rule for target.
ClicPerformance: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ClicPerformance
.PHONY : ClicPerformance

# fast build rule for target.
ClicPerformance/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/build
.PHONY : ClicPerformance/fast

Calorimetry/src/JetAnalyzer.o: Calorimetry/src/JetAnalyzer.cc.o
.PHONY : Calorimetry/src/JetAnalyzer.o

# target to build an object file
Calorimetry/src/JetAnalyzer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Calorimetry/src/JetAnalyzer.cc.o
.PHONY : Calorimetry/src/JetAnalyzer.cc.o

Calorimetry/src/JetAnalyzer.i: Calorimetry/src/JetAnalyzer.cc.i
.PHONY : Calorimetry/src/JetAnalyzer.i

# target to preprocess a source file
Calorimetry/src/JetAnalyzer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Calorimetry/src/JetAnalyzer.cc.i
.PHONY : Calorimetry/src/JetAnalyzer.cc.i

Calorimetry/src/JetAnalyzer.s: Calorimetry/src/JetAnalyzer.cc.s
.PHONY : Calorimetry/src/JetAnalyzer.s

# target to generate assembly for a file
Calorimetry/src/JetAnalyzer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Calorimetry/src/JetAnalyzer.cc.s
.PHONY : Calorimetry/src/JetAnalyzer.cc.s

Calorimetry/src/ShowerStudy.o: Calorimetry/src/ShowerStudy.cxx.o
.PHONY : Calorimetry/src/ShowerStudy.o

# target to build an object file
Calorimetry/src/ShowerStudy.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Calorimetry/src/ShowerStudy.cxx.o
.PHONY : Calorimetry/src/ShowerStudy.cxx.o

Calorimetry/src/ShowerStudy.i: Calorimetry/src/ShowerStudy.cxx.i
.PHONY : Calorimetry/src/ShowerStudy.i

# target to preprocess a source file
Calorimetry/src/ShowerStudy.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Calorimetry/src/ShowerStudy.cxx.i
.PHONY : Calorimetry/src/ShowerStudy.cxx.i

Calorimetry/src/ShowerStudy.s: Calorimetry/src/ShowerStudy.cxx.s
.PHONY : Calorimetry/src/ShowerStudy.s

# target to generate assembly for a file
Calorimetry/src/ShowerStudy.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Calorimetry/src/ShowerStudy.cxx.s
.PHONY : Calorimetry/src/ShowerStudy.cxx.s

Calorimetry/src/TrueMCintoRecoForJets.o: Calorimetry/src/TrueMCintoRecoForJets.cc.o
.PHONY : Calorimetry/src/TrueMCintoRecoForJets.o

# target to build an object file
Calorimetry/src/TrueMCintoRecoForJets.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Calorimetry/src/TrueMCintoRecoForJets.cc.o
.PHONY : Calorimetry/src/TrueMCintoRecoForJets.cc.o

Calorimetry/src/TrueMCintoRecoForJets.i: Calorimetry/src/TrueMCintoRecoForJets.cc.i
.PHONY : Calorimetry/src/TrueMCintoRecoForJets.i

# target to preprocess a source file
Calorimetry/src/TrueMCintoRecoForJets.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Calorimetry/src/TrueMCintoRecoForJets.cc.i
.PHONY : Calorimetry/src/TrueMCintoRecoForJets.cc.i

Calorimetry/src/TrueMCintoRecoForJets.s: Calorimetry/src/TrueMCintoRecoForJets.cc.s
.PHONY : Calorimetry/src/TrueMCintoRecoForJets.s

# target to generate assembly for a file
Calorimetry/src/TrueMCintoRecoForJets.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Calorimetry/src/TrueMCintoRecoForJets.cc.s
.PHONY : Calorimetry/src/TrueMCintoRecoForJets.cc.s

Tracking/src/ClicEfficiencyCalculator.o: Tracking/src/ClicEfficiencyCalculator.cc.o
.PHONY : Tracking/src/ClicEfficiencyCalculator.o

# target to build an object file
Tracking/src/ClicEfficiencyCalculator.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Tracking/src/ClicEfficiencyCalculator.cc.o
.PHONY : Tracking/src/ClicEfficiencyCalculator.cc.o

Tracking/src/ClicEfficiencyCalculator.i: Tracking/src/ClicEfficiencyCalculator.cc.i
.PHONY : Tracking/src/ClicEfficiencyCalculator.i

# target to preprocess a source file
Tracking/src/ClicEfficiencyCalculator.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Tracking/src/ClicEfficiencyCalculator.cc.i
.PHONY : Tracking/src/ClicEfficiencyCalculator.cc.i

Tracking/src/ClicEfficiencyCalculator.s: Tracking/src/ClicEfficiencyCalculator.cc.s
.PHONY : Tracking/src/ClicEfficiencyCalculator.s

# target to generate assembly for a file
Tracking/src/ClicEfficiencyCalculator.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Tracking/src/ClicEfficiencyCalculator.cc.s
.PHONY : Tracking/src/ClicEfficiencyCalculator.cc.s

Tracking/src/ClicTrackingValidate.o: Tracking/src/ClicTrackingValidate.cc.o
.PHONY : Tracking/src/ClicTrackingValidate.o

# target to build an object file
Tracking/src/ClicTrackingValidate.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Tracking/src/ClicTrackingValidate.cc.o
.PHONY : Tracking/src/ClicTrackingValidate.cc.o

Tracking/src/ClicTrackingValidate.i: Tracking/src/ClicTrackingValidate.cc.i
.PHONY : Tracking/src/ClicTrackingValidate.i

# target to preprocess a source file
Tracking/src/ClicTrackingValidate.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Tracking/src/ClicTrackingValidate.cc.i
.PHONY : Tracking/src/ClicTrackingValidate.cc.i

Tracking/src/ClicTrackingValidate.s: Tracking/src/ClicTrackingValidate.cc.s
.PHONY : Tracking/src/ClicTrackingValidate.s

# target to generate assembly for a file
Tracking/src/ClicTrackingValidate.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Tracking/src/ClicTrackingValidate.cc.s
.PHONY : Tracking/src/ClicTrackingValidate.cc.s

Tracking/src/HitResiduals.o: Tracking/src/HitResiduals.cc.o
.PHONY : Tracking/src/HitResiduals.o

# target to build an object file
Tracking/src/HitResiduals.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Tracking/src/HitResiduals.cc.o
.PHONY : Tracking/src/HitResiduals.cc.o

Tracking/src/HitResiduals.i: Tracking/src/HitResiduals.cc.i
.PHONY : Tracking/src/HitResiduals.i

# target to preprocess a source file
Tracking/src/HitResiduals.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Tracking/src/HitResiduals.cc.i
.PHONY : Tracking/src/HitResiduals.cc.i

Tracking/src/HitResiduals.s: Tracking/src/HitResiduals.cc.s
.PHONY : Tracking/src/HitResiduals.s

# target to generate assembly for a file
Tracking/src/HitResiduals.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Tracking/src/HitResiduals.cc.s
.PHONY : Tracking/src/HitResiduals.cc.s

Tracking/src/TrackChecker.o: Tracking/src/TrackChecker.cc.o
.PHONY : Tracking/src/TrackChecker.o

# target to build an object file
Tracking/src/TrackChecker.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Tracking/src/TrackChecker.cc.o
.PHONY : Tracking/src/TrackChecker.cc.o

Tracking/src/TrackChecker.i: Tracking/src/TrackChecker.cc.i
.PHONY : Tracking/src/TrackChecker.i

# target to preprocess a source file
Tracking/src/TrackChecker.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Tracking/src/TrackChecker.cc.i
.PHONY : Tracking/src/TrackChecker.cc.i

Tracking/src/TrackChecker.s: Tracking/src/TrackChecker.cc.s
.PHONY : Tracking/src/TrackChecker.s

# target to generate assembly for a file
Tracking/src/TrackChecker.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/Tracking/src/TrackChecker.cc.s
.PHONY : Tracking/src/TrackChecker.cc.s

source/Conditions/src/CLICRecoConfig.o: source/Conditions/src/CLICRecoConfig.cc.o
.PHONY : source/Conditions/src/CLICRecoConfig.o

# target to build an object file
source/Conditions/src/CLICRecoConfig.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/source/Conditions/src/CLICRecoConfig.cc.o
.PHONY : source/Conditions/src/CLICRecoConfig.cc.o

source/Conditions/src/CLICRecoConfig.i: source/Conditions/src/CLICRecoConfig.cc.i
.PHONY : source/Conditions/src/CLICRecoConfig.i

# target to preprocess a source file
source/Conditions/src/CLICRecoConfig.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/source/Conditions/src/CLICRecoConfig.cc.i
.PHONY : source/Conditions/src/CLICRecoConfig.cc.i

source/Conditions/src/CLICRecoConfig.s: source/Conditions/src/CLICRecoConfig.cc.s
.PHONY : source/Conditions/src/CLICRecoConfig.s

# target to generate assembly for a file
source/Conditions/src/CLICRecoConfig.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClicPerformance.dir/build.make CMakeFiles/ClicPerformance.dir/source/Conditions/src/CLICRecoConfig.cc.s
.PHONY : source/Conditions/src/CLICRecoConfig.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... uninstall"
	@echo "... ClicPerformance"
	@echo "... Calorimetry/src/JetAnalyzer.o"
	@echo "... Calorimetry/src/JetAnalyzer.i"
	@echo "... Calorimetry/src/JetAnalyzer.s"
	@echo "... Calorimetry/src/ShowerStudy.o"
	@echo "... Calorimetry/src/ShowerStudy.i"
	@echo "... Calorimetry/src/ShowerStudy.s"
	@echo "... Calorimetry/src/TrueMCintoRecoForJets.o"
	@echo "... Calorimetry/src/TrueMCintoRecoForJets.i"
	@echo "... Calorimetry/src/TrueMCintoRecoForJets.s"
	@echo "... Tracking/src/ClicEfficiencyCalculator.o"
	@echo "... Tracking/src/ClicEfficiencyCalculator.i"
	@echo "... Tracking/src/ClicEfficiencyCalculator.s"
	@echo "... Tracking/src/ClicTrackingValidate.o"
	@echo "... Tracking/src/ClicTrackingValidate.i"
	@echo "... Tracking/src/ClicTrackingValidate.s"
	@echo "... Tracking/src/HitResiduals.o"
	@echo "... Tracking/src/HitResiduals.i"
	@echo "... Tracking/src/HitResiduals.s"
	@echo "... Tracking/src/TrackChecker.o"
	@echo "... Tracking/src/TrackChecker.i"
	@echo "... Tracking/src/TrackChecker.s"
	@echo "... source/Conditions/src/CLICRecoConfig.o"
	@echo "... source/Conditions/src/CLICRecoConfig.i"
	@echo "... source/Conditions/src/CLICRecoConfig.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

